Moved DataEncoder and DataDecoder protocols from vapor/core repo
vapor/codable-kit pull request #2
Opened 2018-12-01 18:44 UTC by calebkleveter

Relocates the `DataEncoder` and `DataDecoder` protocols from the vapor/core repo to the CodableKit package with a couple minor changes:

- `DataDecoder` doesn't have a `decode` method that takes in `LosslessDataConvertible`. That protocol is not available in this package.
- Adds a `DataCoder` protocol that implements the `DataDecoder` and `DataEncoder` protocols. Not sure if it's needed, but it was only one line so I figured it wouldn't hurt.
- Conforms `PropertyListDecoder` to `DataDecoder` and `PropertyListEncoder` to `DataEncoder`.

2019-02-11 23:09 UTC, tanner0101 approved these changes

2019-02-11 23:09 UTC, tanner0101 commented
Let's just wait for https://github.com/vapor/codable-kit/pull/6 so that we can have CI approve this one 👍

2019-02-12 15:35 UTC, tanner0101 requested changes
Let's add conveniences for getting the `Decoder` via unwrapper.

```swift
JSONDecoder.decoder(with: data) // -> _JSONDecoder
```

2019-02-12 15:51 UTC, tanner0101 commented on Sources/CodableKit/DataCoder.swift
> +extension PropertyListDecoder: DataDecoder { }
I think this just needs to be wrapped in `#if os(macOS)`

2019-02-12 17:49 UTC, tanner0101 commented on Sources/CodableKit/DataCoder.swift
> +    public static func decoder(with data: Data)throws -> Decoder {
```suggestion
    public static func decoder(from data: Data) throws -> Decoder {
```

Missing space + I think using the `from` label makes more sense.

2019-02-12 17:49 UTC, tanner0101 commented on Sources/CodableKit/DataCoder.swift
> +    public static func decoder(with data: Data)throws -> Decoder {
```suggestion
    public static func decoder(from data: Data) throws -> Decoder {
```
same as above

2019-02-12 17:55 UTC, calebkleveter commented
@tanner0101 Done 👍 1+

2019-02-12 17:56 UTC, tanner0101 submitted a review, later dismissed
Good to merge after this one.

2019-02-12 17:56 UTC, tanner0101 commented on Sources/CodableKit/DataCoder.swift
> +public protocol DataCoder: DataEncoder, DataDecoder {}
```suggestion
public typealias DataCoder = DataEncoder & DataDecoder
```

That way if you do `extension MyEncoder: DataEncoder, DataDecoder { }` you will still technically conform to `DataCoder`

2019-02-12 18:01 UTC, tanner0101 approved these changes

2019-02-12 18:01 UTC, merged

2019-02-12 18:01 UTC, penny-coin commented
Hey @calebkleveter, you just merged a pull request, have a coin! 

You now have 439 coins.