Created CONTRIBUTING.md doc with 'Maintainers' section
vapor/codable-kit pull request #3
Opened 2019-01-17 18:32 UTC by calebkleveter

2019-01-17 18:34 UTC, MrLotU requested changes
Could you copy nio-kit's CONTRIBUTING.md's contents in this one too? So that it provides actual Contributing guidelines too?

2019-01-17 18:39 UTC, calebkleveter commented
@MrLotU Added!

2019-01-17 18:39 UTC, MrLotU approved these changes

2019-01-23 21:19 UTC, tanner0101 requested changes
Just some small issues, but overall looks great 👍

2019-01-23 21:19 UTC, tanner0101 commented on .github/CONTRIBUTING.md
> +Go ahead and [open a new issue](https://github.com/vapor-community/nio-kit/issues/new). The team will be notified and we should get back to you shortly.
wrong link for the new issue here.

2019-01-23 21:19 UTC, tanner0101 commented on .github/CONTRIBUTING.md
> +# Contributing
for markdown docs, we should try to keep line length at a max of 70. helps a lot with diffs!

2019-01-23 21:19 UTC, tanner0101 commented on .github/CONTRIBUTING.md
> +- [Open a new issue](https://github.com/vapor-community/nio-kit/issues/new) or post in the #ideas or #development channel on the [Discord server](http://vapor.team/). This lets the us know what you h
link wrong

2019-01-23 21:34 UTC, calebkleveter commented
@tanner0101 👍

2019-01-28 21:56 UTC, tanner0101 approved these changes

2019-02-11 23:09 UTC, tanner0101 approved these changes

2019-02-12 15:40 UTC, merged

2019-02-12 15:40 UTC, penny-coin commented
Hey @calebkleveter, you just merged a pull request, have a coin! 

You now have 437 coins.